<div class="home-content">

{{block type="featuredproduct/featuredproduct" name="featuredproduct" template="themevast/featuredproduct/featuredproduct.phtml" }}
{{block type="cms/block" block_id="home1_banner_content1"}}
{{block type="newproductslider/newproductslider" name="newproductslider" template="themevast/newproductslider/newproductslider.phtml"}}
{{block type="cms/block" block_id="home1_banner_content2"}}
{{block type="bestsellerslider/bestsellerslider" name="bestsellerslider" template="themevast/bestsellerslider/bestsellerslider.phtml" }}
</div>