<?php
class Mivec_Product_Block_Adminhtml_Quote_Edit_Tabs extends Mage_Adminhtml_Block_Widget_Tabs
{
    public function __construct(array $args = array())
    {
        parent::__construct($args);
        $this->setId("quote_tabs");
        $this->setDestElementId("edit_form");
        $this->setTitle("Product Quotes");
    }

    public function _beforeToHtml()
    {
        $this->addTab("form_section" , array(
            "label"     => "Quote",
            "content"   => $this->getLayout()->createBlock("product/adminhtml_quote_edit_tab_form")->toHtml()
        ));
        return parent::_beforeToHtml(); // TODO: Change the autogenerated stub
    }
}